### ISSUE TITLE
Milestone 1 - Prototype

### ISSUE THREAD

**Issue by redtux** [pandainfo/docs#43]
@redtux commented on [Tue Dec 22 2020](https://github.com/pandainfo/panda/issues/21)

Our prototype will be released as a bundle, consisting at least of the following components:
* [ ] Epic: Shop #45 
* [ ] Epic: Static Sites (About, Contact, etc.) #48 
* [ ] Epic: Multisite Network (MU) #49 
* [ ] Epic: Basic Theme #50 
* [ ] Epic: ERP & eCommerce Management #51  
* [ ] Epic: CRM & Newsletter Management #52 
* [ ] Epic: Admin Dashboard #53 
* [ ] Epic: User Management & RBAC #54 
* [ ] Epic: Customized Login #55 

---

@github-actions[bot] commented on [Mon Feb 22 2021](https://github.com/pandainfo/panda/issues/21#issuecomment-782987657)

This issue has been hanging around a bit too long. If needed, please update or comment.
