### ISSUE TITLE
Milestone: January 2021 (Prototype)

### ISSUE THREAD

**Issue by redtux** [pandainfo/docs#44]
@redtux commented on [Tue Dec 22 2020](https://github.com/pandainfo/panda/issues/21)

Our prototype will be released as a bundle, consisting at least of the following components:
* [ ] Epic: Multisite Network (MU) #7
* [ ] Epic: Basic Theme #8
* [ ] Epic: Shop #9
* [ ] Epic: ERP & eCommerce Management #10
* [ ] Epic: CRM & Newsletter Management #11
* [ ] Epic: Admin Dashboard #20
* [ ] Epic: User Management & RBAC #22
* [ ] Epic: Customized Login #23
* [ ] Epic: Static Sites (About, Contact, etc.) #24

---

@github-actions[bot] commented on [Mon Feb 22 2021](https://github.com/pandainfo/panda/issues/21#issuecomment-782987657)

This issue has been hanging around a bit too long. If needed, please update or comment.

**Comment by redtux** [comment]
Duplicate of #43
