### ISSUE TITLE
Epic: List Panda Milestones

### ISSUE THREAD

**Issue by redtux** [pandainfo/docs#47]
This list of Panda milestones shall be continuously updated.

**Comment by redtux** [comment]
> Note: [ZenHub Roadmap] allows separate time periods for Projects, [Milestones], and [Epics]. The following list shows our ZenHub projects, being the top hierarchy.

[ZenHub Roadmap]: https://app.zenhub.com/workspaces/panda-6010bbc5d8bd2f000e2c26f3/roadmap
[Milestones]: https://app.zenhub.com/workspaces/panda-6010bbc5d8bd2f000e2c26f3/milestones
[Epics]: https://github.com/pandainfo/community/labels/Epic

- [ ] ⚙️ **Panda Core** is based on ClassicPress and the e-commerce extension ClassicCommerce. Order, title and customer data is recorded and processed in the store system. Our focus is on interfaces and distribution channels for the German-language book trade. #42

> 📜 The complete software package consists of:

- [ ] 🛍️ **Panda Shop** - enables 24/7 shopping at the local bookstore of choice with a search system, customer area, coupon management, loyalty card system, and more #45
- [ ] 🗄️ **Panda Cloud** - Data storage for automated filing of e-mail invoices as well as EDI messages from the IBU clearing center including calendar & contact management for teams.
- [ ] 🌀 **Panda for Books** - an ONIX product database for all catalog items including a corresponding bibliography system, address management, stock management/warehouse management, and a native desktop client for PC and Raspberry Pi (based on buX) with VLB interface to the webshop.
- [ ] 📦 **Panda ERP** - with EDI interface (IBU) to publisher deliveries & book distributors, dispatch & stock control book (SCM), electronic delivery bill (ELS) as well as an inventory module with the possibility to create and print barcode labels, invoices & delivery bills #51
- [ ] 🏷️ **Panda POS** - point of sale for PCs, tablets, smartphones & IoT devices (cash register) with automated item matching between stores, webshop & product database (ERP)
- [ ] 📞 **Panda CRM** - for customer care and acquisition, newsletter management & online marketing #52
- [ ] 💶 **Panda Accounting** - for payment system, invoicing, payment reminders and financial accounting
- [ ] 📕 **Panda DB** - database administration made easy for somewhat more complex requirements
- [ ] ️📩 **Panda Mail** - Orders mailbox for incoming order requests and reclamations as well as Invoice mailbox for incoming bills and delivery bills, archiving in the **Panda Cloud** and webmail interface with close integration to CMS publishing system, webshop, cloud, CRM & ERP
- [ ] 📥 **Panda Clearing Center** - SFTP box of the IBU clearing center including cloud synchronization for order dispatch, delivery bill & invoice receipt, and for the collection of the "Yellow Pages" as well as the daily updates of report numbers (availability) & product data of the warehouse delivery
- [ ] 📖 **Panda Releases** - include ongoing enhancements as an installation package & container
