### ISSUE TITLE
Epic: Static Sites

### ISSUE THREAD

**Issue by redtux** [pandainfo/docs#48]
@redtux commented on [Wed Dec 23 2020](https://github.com/pandainfo/panda/issues/24)

Create static sites like TOS, contact, and about.
* [ ] About #67 
* [ ] Contact #68 
* [ ] Privacy Policy & Cookie Policy #69 
* [ ] Terms and Conditions / TOS #70 
* [ ] Notice of Withdrawal #71 
* [ ] Imprint #72 

---

@github-actions[bot] commented on [Mon Feb 22 2021](https://github.com/pandainfo/panda/issues/24#issuecomment-782987639)

This issue has been hanging around a bit too long. If needed, please update or comment.
