### ISSUE TITLE
Epic: .github Community Health Files

### ISSUE THREAD

**Issue by redtux** [pandainfo/docs#75]
> 💡 These are [template files] for all repositories maintained or created by the [pandainfo](https://github.com/pandainfo) organization.

### Documents

- [ ] Initialize project and create LICENSE document
- [ ] Create Readme with About, Contributing, and License section
- [ ] Create AUTHORS file listing significant contributors
- [ ] Create Community Guidelines Document linking to relevant resources
- [ ] Create Contribution Guidelines with an About, Coding Standards, Contact, and Help section explaining issue and pull request templates
- [ ] Create Contribution License Agreement (CLA)
- [ ] Create Project Governance Document
- [ ] Create Security Guidelines
- [ ] Create Credits Document with a Software, Content, Fonts, Images, and Logo section
- [ ] Create Glossary Document with relevant terms and abbreviations
- [ ] Add Support Resources

### Config files

- [ ] Define Code Owners
- [ ] Define [Git Attributes](https://www.git-scm.com/docs/gitattributes)
- [ ] Specify [Git Ignore Rules](https://git-scm.com/docs/gitignore) for untracked files
- [ ] Define Panda Coding Styles with EditorConfig
- [ ] Define Bad Names in `.mailmap`
- [ ] Create GitHub CI to automatically lint markdown files using markdownlint
- [ ] Create `package.json` to use [Conventional Changelog](https://github.com/conventional-changelog/conventional-changelog)
- [ ] Use automated version management and package publishing via [Semantic Release](https://semantic-release.gitbook.io/semantic-release/)
- [ ] Use [Gitmoji with Commitizen](https://github.com/ngryman/cz-emoji)
- [ ] Use [Devmoji](https://github.com/folke/devmoji)
- [ ] Force Semantic Pull Requests via `.github/semantic.yml` using [Probot](https://probot.github.io/)

### Issue templates

Create a default templates for the following types of issues:

- [ ] Questions (`config.yml`)
- [ ] Pull requests
- [ ] Bug reports
- [ ] Feature requests

### Badges

- [ ] Customize our [social media preview image]
- [ ] Create a default `FUNDING.yml` file for all repositories
  - [ ] [GitHub Sponsors](https://github.com/sponsors)
  - [ ] [Liberapay](https://liberapay.com/)
  - [ ] [Open Collective](https://opencollective.com/)
  - [ ] [Patreon](https://www.patreon.com/)
  - [ ] [PayPal](https://www.paypal.com/paypalme/)

[social media preview image]: https://docs.github.com/en/github/administering-a-repository/customizing-your-repositorys-social-media-preview
[template files]: https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file "Creating a default community health file on GitHub"
